# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\TrnglCalcApp.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TrnglCalculatorApp(object):
    def setupUi(self, TrnglCalculatorApp):
        TrnglCalculatorApp.setObjectName("TrnglCalculatorApp")
        TrnglCalculatorApp.resize(614, 553)
        TrnglCalculatorApp.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(TrnglCalculatorApp)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setAutoFillBackground(True)
        self.frame_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.labelR = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelR.setFont(font)
        self.labelR.setObjectName("labelR")
        self.gridLayout.addWidget(self.labelR, 3, 0, 1, 1)
        self.lineEdit_b = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_b.setObjectName("lineEdit_b")
        self.gridLayout.addWidget(self.lineEdit_b, 2, 6, 1, 1)
        self.label_a = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_a.setFont(font)
        self.label_a.setObjectName("label_a")
        self.gridLayout.addWidget(self.label_a, 0, 5, 1, 1)
        self.lineEdit_c = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_c.setObjectName("lineEdit_c")
        self.gridLayout.addWidget(self.lineEdit_c, 3, 6, 1, 1)
        self.label_c = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_c.setFont(font)
        self.label_c.setObjectName("label_c")
        self.gridLayout.addWidget(self.label_c, 3, 5, 1, 1)
        self.labelGamma = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelGamma.setFont(font)
        self.labelGamma.setObjectName("labelGamma")
        self.gridLayout.addWidget(self.labelGamma, 3, 2, 1, 1)
        self.label_b = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_b.setFont(font)
        self.label_b.setObjectName("label_b")
        self.gridLayout.addWidget(self.label_b, 2, 5, 1, 1)
        self.labelP = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelP.setFont(font)
        self.labelP.setObjectName("labelP")
        self.gridLayout.addWidget(self.labelP, 0, 0, 1, 1)
        self.labelBeta = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelBeta.setFont(font)
        self.labelBeta.setObjectName("labelBeta")
        self.gridLayout.addWidget(self.labelBeta, 2, 2, 1, 1)
        self.labelArea = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelArea.setFont(font)
        self.labelArea.setObjectName("labelArea")
        self.gridLayout.addWidget(self.labelArea, 2, 0, 1, 1)
        self.labelAlpha = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelAlpha.setFont(font)
        self.labelAlpha.setObjectName("labelAlpha")
        self.gridLayout.addWidget(self.labelAlpha, 0, 2, 1, 1)
        self.lineEdit_a = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_a.setObjectName("lineEdit_a")
        self.gridLayout.addWidget(self.lineEdit_a, 0, 6, 1, 1)
        self.Area = QtWidgets.QLineEdit(self.frame_2)
        self.Area.setObjectName("Area")
        self.gridLayout.addWidget(self.Area, 2, 1, 1, 1)
        self.alpha = QtWidgets.QLineEdit(self.frame_2)
        self.alpha.setObjectName("alpha")
        self.gridLayout.addWidget(self.alpha, 0, 3, 1, 1)
        self.Perimeter = QtWidgets.QLineEdit(self.frame_2)
        self.Perimeter.setObjectName("Perimeter")
        self.gridLayout.addWidget(self.Perimeter, 0, 1, 1, 1)
        self.Radius = QtWidgets.QLineEdit(self.frame_2)
        self.Radius.setObjectName("Radius")
        self.gridLayout.addWidget(self.Radius, 3, 1, 1, 1)
        self.beta = QtWidgets.QLineEdit(self.frame_2)
        self.beta.setObjectName("beta")
        self.gridLayout.addWidget(self.beta, 2, 3, 1, 1)
        self.gamma = QtWidgets.QLineEdit(self.frame_2)
        self.gamma.setObjectName("gamma")
        self.gridLayout.addWidget(self.gamma, 3, 3, 1, 1)
        self.gridLayout_3.addWidget(self.frame_2, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.frame)
        self.graphicsView.setAutoFillBackground(False)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.gridLayout_3.addWidget(self.frame, 1, 0, 1, 2)
        self.frame_1 = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.frame_1.setFont(font)
        self.frame_1.setMouseTracking(True)
        self.frame_1.setAcceptDrops(False)
        self.frame_1.setAutoFillBackground(True)
        self.frame_1.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_1.setLineWidth(1)
        self.frame_1.setMidLineWidth(1)
        self.frame_1.setObjectName("frame_1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBox_1 = QtWidgets.QComboBox(self.frame_1)
        self.comboBox_1.setEditable(False)
        self.comboBox_1.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.comboBox_1.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_1.setObjectName("comboBox_1")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_1, 0, 0, 1, 1)
        self.CalcBtn = QtWidgets.QPushButton(self.frame_1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CalcBtn.setFont(font)
        self.CalcBtn.setObjectName("CalcBtn")
        self.gridLayout_2.addWidget(self.CalcBtn, 8, 0, 1, 2)
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_1)
        self.comboBox_2.setEditable(False)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_2, 3, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.frame_1)
        self.comboBox_3.setEditable(False)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_3, 6, 0, 1, 1)
        self.sideC = QtWidgets.QLineEdit(self.frame_1)
        self.sideC.setObjectName("sideC")
        self.gridLayout_2.addWidget(self.sideC, 6, 1, 1, 1)
        self.sideB = QtWidgets.QLineEdit(self.frame_1)
        self.sideB.setObjectName("sideB")
        self.gridLayout_2.addWidget(self.sideB, 3, 1, 1, 1)
        self.sideA = QtWidgets.QLineEdit(self.frame_1)
        self.sideA.setObjectName("sideA")
        self.gridLayout_2.addWidget(self.sideA, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frame_1, 0, 0, 1, 1)
        TrnglCalculatorApp.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TrnglCalculatorApp)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 614, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        TrnglCalculatorApp.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TrnglCalculatorApp)
        self.statusbar.setObjectName("statusbar")
        TrnglCalculatorApp.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(TrnglCalculatorApp)
        self.toolBar.setObjectName("toolBar")
        TrnglCalculatorApp.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionExit = QtWidgets.QAction(TrnglCalculatorApp)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon)
        self.actionExit.setObjectName("actionExit")
        self.actionPreferences = QtWidgets.QAction(TrnglCalculatorApp)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/preferences.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPreferences.setIcon(icon1)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionMinimize = QtWidgets.QAction(TrnglCalculatorApp)
        self.actionMinimize.setObjectName("actionMinimize")
        self.actionNew = QtWidgets.QAction(TrnglCalculatorApp)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon2)
        self.actionNew.setObjectName("actionNew")
        self.actionSave = QtWidgets.QAction(TrnglCalculatorApp)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/savefile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon3)
        self.actionSave.setObjectName("actionSave")
        self.actionOpen = QtWidgets.QAction(TrnglCalculatorApp)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon4)
        self.actionOpen.setObjectName("actionOpen")
        self.actionAbout = QtWidgets.QAction(TrnglCalculatorApp)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSave_as = QtWidgets.QAction(TrnglCalculatorApp)
        self.actionSave_as.setObjectName("actionSave_as")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionPreferences)
        self.menuHelp.addAction(self.actionAbout)
        self.menuWindow.addAction(self.actionMinimize)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionPreferences)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)
        self.labelR.setBuddy(self.sideB)
        self.label_a.setBuddy(self.lineEdit_a)
        self.label_c.setBuddy(self.lineEdit_c)
        self.labelGamma.setBuddy(self.Radius)
        self.label_b.setBuddy(self.lineEdit_b)
        self.labelP.setBuddy(self.sideC)
        self.labelBeta.setBuddy(self.alpha)
        self.labelArea.setBuddy(self.sideA)
        self.labelAlpha.setBuddy(self.Perimeter)

        self.retranslateUi(TrnglCalculatorApp)
        QtCore.QMetaObject.connectSlotsByName(TrnglCalculatorApp)
        TrnglCalculatorApp.setTabOrder(self.comboBox_1, self.CalcBtn)

    def retranslateUi(self, TrnglCalculatorApp):
        _translate = QtCore.QCoreApplication.translate
        TrnglCalculatorApp.setWindowTitle(_translate("TrnglCalculatorApp", "Triangle Calculator"))
        self.labelR.setText(_translate("TrnglCalculatorApp", "R ="))
        self.lineEdit_b.setPlaceholderText(_translate("TrnglCalculatorApp", "0"))
        self.label_a.setText(_translate("TrnglCalculatorApp", "a ="))
        self.lineEdit_c.setPlaceholderText(_translate("TrnglCalculatorApp", "0"))
        self.label_c.setText(_translate("TrnglCalculatorApp", "c ="))
        self.labelGamma.setText(_translate("TrnglCalculatorApp", "ɣ ="))
        self.label_b.setText(_translate("TrnglCalculatorApp", "b ="))
        self.labelP.setText(_translate("TrnglCalculatorApp", "P = "))
        self.labelBeta.setText(_translate("TrnglCalculatorApp", "β ="))
        self.labelArea.setText(_translate("TrnglCalculatorApp", "A ="))
        self.labelAlpha.setText(_translate("TrnglCalculatorApp", "α ="))
        self.lineEdit_a.setPlaceholderText(_translate("TrnglCalculatorApp", "0"))
        self.Area.setPlaceholderText(_translate("TrnglCalculatorApp", "0"))
        self.alpha.setPlaceholderText(_translate("TrnglCalculatorApp", "0"))
        self.Perimeter.setPlaceholderText(_translate("TrnglCalculatorApp", "0"))
        self.Radius.setPlaceholderText(_translate("TrnglCalculatorApp", "0"))
        self.beta.setPlaceholderText(_translate("TrnglCalculatorApp", "0"))
        self.gamma.setPlaceholderText(_translate("TrnglCalculatorApp", "0"))
        self.comboBox_1.setCurrentText(_translate("TrnglCalculatorApp", "a"))
        self.comboBox_1.setItemText(0, _translate("TrnglCalculatorApp", "a", " "))
        self.comboBox_1.setItemText(1, _translate("TrnglCalculatorApp", "b"))
        self.comboBox_1.setItemText(2, _translate("TrnglCalculatorApp", "c"))
        self.comboBox_1.setItemText(3, _translate("TrnglCalculatorApp", "α"))
        self.comboBox_1.setItemText(4, _translate("TrnglCalculatorApp", "β"))
        self.comboBox_1.setItemText(5, _translate("TrnglCalculatorApp", "ɣ"))
        self.CalcBtn.setText(_translate("TrnglCalculatorApp", "Calculate"))
        self.comboBox_2.setCurrentText(_translate("TrnglCalculatorApp", "c"))
        self.comboBox_2.setItemText(0, _translate("TrnglCalculatorApp", "c"))
        self.comboBox_2.setItemText(1, _translate("TrnglCalculatorApp", "a"))
        self.comboBox_2.setItemText(2, _translate("TrnglCalculatorApp", "b"))
        self.comboBox_2.setItemText(3, _translate("TrnglCalculatorApp", "α"))
        self.comboBox_2.setItemText(4, _translate("TrnglCalculatorApp", "β"))
        self.comboBox_2.setItemText(5, _translate("TrnglCalculatorApp", "ɣ"))
        self.comboBox_3.setCurrentText(_translate("TrnglCalculatorApp", "b"))
        self.comboBox_3.setItemText(0, _translate("TrnglCalculatorApp", "b"))
        self.comboBox_3.setItemText(1, _translate("TrnglCalculatorApp", "a"))
        self.comboBox_3.setItemText(2, _translate("TrnglCalculatorApp", "c"))
        self.comboBox_3.setItemText(3, _translate("TrnglCalculatorApp", "α"))
        self.comboBox_3.setItemText(4, _translate("TrnglCalculatorApp", "β"))
        self.comboBox_3.setItemText(5, _translate("TrnglCalculatorApp", "ɣ"))
        self.sideC.setPlaceholderText(_translate("TrnglCalculatorApp", "0"))
        self.sideB.setPlaceholderText(_translate("TrnglCalculatorApp", "0"))
        self.sideA.setPlaceholderText(_translate("TrnglCalculatorApp", "0"))
        self.menuFile.setTitle(_translate("TrnglCalculatorApp", "File"))
        self.menuEdit.setTitle(_translate("TrnglCalculatorApp", "Settings"))
        self.menuHelp.setTitle(_translate("TrnglCalculatorApp", "Help"))
        self.menuWindow.setTitle(_translate("TrnglCalculatorApp", "Window"))
        self.toolBar.setWindowTitle(_translate("TrnglCalculatorApp", "toolBar"))
        self.actionExit.setText(_translate("TrnglCalculatorApp", "Exit"))
        self.actionExit.setShortcut(_translate("TrnglCalculatorApp", "Ctrl+Q"))
        self.actionPreferences.setText(_translate("TrnglCalculatorApp", "Preferences..."))
        self.actionMinimize.setText(_translate("TrnglCalculatorApp", "Minimize"))
        self.actionMinimize.setShortcut(_translate("TrnglCalculatorApp", "Ctrl+M"))
        self.actionNew.setText(_translate("TrnglCalculatorApp", "New"))
        self.actionNew.setShortcut(_translate("TrnglCalculatorApp", "Ctrl+N"))
        self.actionSave.setText(_translate("TrnglCalculatorApp", "Save"))
        self.actionSave.setShortcut(_translate("TrnglCalculatorApp", "Ctrl+S"))
        self.actionOpen.setText(_translate("TrnglCalculatorApp", "Open"))
        self.actionOpen.setShortcut(_translate("TrnglCalculatorApp", "Ctrl+O"))
        self.actionAbout.setText(_translate("TrnglCalculatorApp", "About Calculator"))
        self.actionSave_as.setText(_translate("TrnglCalculatorApp", "Save as..."))

import icons_rc
