# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TrnglCalcApp.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TrnglCalculatorApp(object):
    def setupUi(self, TrnglCalculatorApp):
        TrnglCalculatorApp.setObjectName("TrnglCalculatorApp")
        TrnglCalculatorApp.resize(542, 183)
        self.centralwidget = QtWidgets.QWidget(TrnglCalculatorApp)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.labelA = QtWidgets.QLabel(self.centralwidget)
        self.labelA.setObjectName("labelA")
        self.gridLayout.addWidget(self.labelA, 0, 0, 1, 1)
        self.sideA = QtWidgets.QLineEdit(self.centralwidget)
        self.sideA.setObjectName("sideA")
        self.gridLayout.addWidget(self.sideA, 0, 1, 1, 1)
        self.labelP = QtWidgets.QLabel(self.centralwidget)
        self.labelP.setObjectName("labelP")
        self.gridLayout.addWidget(self.labelP, 0, 2, 1, 1)
        self.Perimeter = QtWidgets.QLineEdit(self.centralwidget)
        self.Perimeter.setObjectName("Perimeter")
        self.gridLayout.addWidget(self.Perimeter, 0, 3, 1, 1)
        self.labelAlpha = QtWidgets.QLabel(self.centralwidget)
        self.labelAlpha.setObjectName("labelAlpha")
        self.gridLayout.addWidget(self.labelAlpha, 0, 4, 1, 1)
        self.alpha = QtWidgets.QLineEdit(self.centralwidget)
        self.alpha.setObjectName("alpha")
        self.gridLayout.addWidget(self.alpha, 0, 5, 1, 1)
        self.labelB = QtWidgets.QLabel(self.centralwidget)
        self.labelB.setObjectName("labelB")
        self.gridLayout.addWidget(self.labelB, 1, 0, 1, 1)
        self.sideB = QtWidgets.QLineEdit(self.centralwidget)
        self.sideB.setObjectName("sideB")
        self.gridLayout.addWidget(self.sideB, 1, 1, 1, 1)
        self.labelArea = QtWidgets.QLabel(self.centralwidget)
        self.labelArea.setObjectName("labelArea")
        self.gridLayout.addWidget(self.labelArea, 1, 2, 1, 1)
        self.Area = QtWidgets.QLineEdit(self.centralwidget)
        self.Area.setObjectName("Area")
        self.gridLayout.addWidget(self.Area, 1, 3, 1, 1)
        self.labelBeta = QtWidgets.QLabel(self.centralwidget)
        self.labelBeta.setObjectName("labelBeta")
        self.gridLayout.addWidget(self.labelBeta, 1, 4, 1, 1)
        self.beta = QtWidgets.QLineEdit(self.centralwidget)
        self.beta.setObjectName("beta")
        self.gridLayout.addWidget(self.beta, 1, 5, 1, 1)
        self.labelC = QtWidgets.QLabel(self.centralwidget)
        self.labelC.setObjectName("labelC")
        self.gridLayout.addWidget(self.labelC, 2, 0, 1, 1)
        self.sideC = QtWidgets.QLineEdit(self.centralwidget)
        self.sideC.setObjectName("sideC")
        self.gridLayout.addWidget(self.sideC, 2, 1, 1, 1)
        self.labelR = QtWidgets.QLabel(self.centralwidget)
        self.labelR.setObjectName("labelR")
        self.gridLayout.addWidget(self.labelR, 2, 2, 1, 1)
        self.Radius = QtWidgets.QLineEdit(self.centralwidget)
        self.Radius.setObjectName("Radius")
        self.gridLayout.addWidget(self.Radius, 2, 3, 1, 1)
        self.labelGamma = QtWidgets.QLabel(self.centralwidget)
        self.labelGamma.setObjectName("labelGamma")
        self.gridLayout.addWidget(self.labelGamma, 2, 4, 1, 1)
        self.gamma = QtWidgets.QLineEdit(self.centralwidget)
        self.gamma.setObjectName("gamma")
        self.gridLayout.addWidget(self.gamma, 2, 5, 1, 1)
        self.CalcBtn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.CalcBtn.setFont(font)
        self.CalcBtn.setObjectName("CalcBtn")
        self.gridLayout.addWidget(self.CalcBtn, 3, 1, 1, 1)
        TrnglCalculatorApp.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TrnglCalculatorApp)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 542, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        TrnglCalculatorApp.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TrnglCalculatorApp)
        self.statusbar.setObjectName("statusbar")
        TrnglCalculatorApp.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(TrnglCalculatorApp)
        self.toolBar.setObjectName("toolBar")
        TrnglCalculatorApp.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionExit = QtWidgets.QAction(TrnglCalculatorApp)
        self.actionExit.setObjectName("actionExit")
        self.actionOptions = QtWidgets.QAction(TrnglCalculatorApp)
        self.actionOptions.setObjectName("actionOptions")
        self.actionMinimize = QtWidgets.QAction(TrnglCalculatorApp)
        self.actionMinimize.setObjectName("actionMinimize")
        self.actionNew = QtWidgets.QAction(TrnglCalculatorApp)
        self.actionNew.setObjectName("actionNew")
        self.actionSave = QtWidgets.QAction(TrnglCalculatorApp)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionOptions)
        self.menuWindow.addAction(self.actionMinimize)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionOptions)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)
        self.labelA.setBuddy(self.sideA)
        self.labelP.setBuddy(self.Perimeter)
        self.labelAlpha.setBuddy(self.alpha)
        self.labelB.setBuddy(self.sideB)
        self.labelArea.setBuddy(self.Area)
        self.labelBeta.setBuddy(self.beta)
        self.labelC.setBuddy(self.sideC)
        self.labelR.setBuddy(self.Radius)
        self.labelGamma.setBuddy(self.gamma)

        self.retranslateUi(TrnglCalculatorApp)
        QtCore.QMetaObject.connectSlotsByName(TrnglCalculatorApp)
        TrnglCalculatorApp.setTabOrder(self.sideA, self.sideB)
        TrnglCalculatorApp.setTabOrder(self.sideB, self.sideC)
        TrnglCalculatorApp.setTabOrder(self.sideC, self.CalcBtn)
        TrnglCalculatorApp.setTabOrder(self.CalcBtn, self.Perimeter)
        TrnglCalculatorApp.setTabOrder(self.Perimeter, self.Area)
        TrnglCalculatorApp.setTabOrder(self.Area, self.Radius)
        TrnglCalculatorApp.setTabOrder(self.Radius, self.alpha)
        TrnglCalculatorApp.setTabOrder(self.alpha, self.beta)
        TrnglCalculatorApp.setTabOrder(self.beta, self.gamma)

    def retranslateUi(self, TrnglCalculatorApp):
        _translate = QtCore.QCoreApplication.translate
        TrnglCalculatorApp.setWindowTitle(_translate("TrnglCalculatorApp", "Triangle Calculator"))
        self.labelA.setText(_translate("TrnglCalculatorApp", "Side A"))
        self.sideA.setPlaceholderText(_translate("TrnglCalculatorApp", "0"))
        self.labelP.setText(_translate("TrnglCalculatorApp", "P = "))
        self.Perimeter.setPlaceholderText(_translate("TrnglCalculatorApp", "0"))
        self.labelAlpha.setText(_translate("TrnglCalculatorApp", "alpha ="))
        self.alpha.setPlaceholderText(_translate("TrnglCalculatorApp", "0"))
        self.labelB.setText(_translate("TrnglCalculatorApp", "Side B"))
        self.sideB.setPlaceholderText(_translate("TrnglCalculatorApp", "0"))
        self.labelArea.setText(_translate("TrnglCalculatorApp", "A ="))
        self.Area.setPlaceholderText(_translate("TrnglCalculatorApp", "0"))
        self.labelBeta.setText(_translate("TrnglCalculatorApp", "beta ="))
        self.beta.setPlaceholderText(_translate("TrnglCalculatorApp", "0"))
        self.labelC.setText(_translate("TrnglCalculatorApp", "Side C"))
        self.sideC.setPlaceholderText(_translate("TrnglCalculatorApp", "0"))
        self.labelR.setText(_translate("TrnglCalculatorApp", "R ="))
        self.Radius.setPlaceholderText(_translate("TrnglCalculatorApp", "0"))
        self.labelGamma.setText(_translate("TrnglCalculatorApp", "gamma ="))
        self.gamma.setPlaceholderText(_translate("TrnglCalculatorApp", "0"))
        self.CalcBtn.setText(_translate("TrnglCalculatorApp", "Calculate"))
        self.menuFile.setTitle(_translate("TrnglCalculatorApp", "File"))
        self.menuEdit.setTitle(_translate("TrnglCalculatorApp", "Settings"))
        self.menuHelp.setTitle(_translate("TrnglCalculatorApp", "Help"))
        self.menuWindow.setTitle(_translate("TrnglCalculatorApp", "Window"))
        self.toolBar.setWindowTitle(_translate("TrnglCalculatorApp", "toolBar"))
        self.actionExit.setText(_translate("TrnglCalculatorApp", "Exit"))
        self.actionExit.setShortcut(_translate("TrnglCalculatorApp", "Ctrl+Q"))
        self.actionOptions.setText(_translate("TrnglCalculatorApp", "Preferences..."))
        self.actionMinimize.setText(_translate("TrnglCalculatorApp", "Minimize"))
        self.actionMinimize.setShortcut(_translate("TrnglCalculatorApp", "Ctrl+M"))
        self.actionNew.setText(_translate("TrnglCalculatorApp", "New"))
        self.actionSave.setText(_translate("TrnglCalculatorApp", "Save"))

import icons
